### ISSUE TITLE
Fixing problems inheriting of the use of read/write.csv in RMassBank

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBankData#1]
Inheriting from use of old-style `read.csv` / `write.csv`, many problems and workarounds are required in infolist handling in RMassBank. For example underscores are truncated to dots and so on. In RMassBank tidy csv import / export is implemented and thus the infolists need some cosmetic change in column names.

**Comment by sneumann** [comment]
Sidenote: ` read.table()` has the `check.names` argument to suppress making R-compliant column names. In return that means that special characters in CSV column names may need special casing elsewhere in the code. Yours, Steffen

**Comment by tsufz** [comment]
Yes, thanks. However, `read.csv` has a real performance problem: https://arbor-analytics.com/post/2022-05-19-reading-in-data-quickly-in-r/

**Comment by tsufz** [comment]
Solved in #2
