### ISSUE TITLE
Narcotics stored dataset is outdated

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBankData#3]
```
> # In the really evaluated workflow, we do the following:
> # we run steps 1 through 3, load the recalibration curve from a stored workflow
> # and recalibrate the data using that curve.
> storedW <- loadMsmsWorkspace(system.file("results/pH_narcotics_RF.RData", 
+ 				package="RMassBankData"))
```

Warning: You are loading an archive from an old RMassBank version. The aggregate tables are not loaded from the original object, but recomputed.Warning: If you hand-edited any aggregate table, the information might not be retained in the new object.

**Comment by meowcat** [comment]
This is intended, and tests whether the old dataset can successfully be upgraded to the new format.
